### ISSUE TITLE
Missing some name semantics

### ISSUE THREAD

**Issue by acabal** [drgrigg/anthony-trollope_barchester-towers#2]
Many abbreviated names are missing `<abbr class="name">`; for example T. Towers, S. Harding, etc. Use this regex to help find them: `[A-Z]\.\s*([A-Z]\.\s*)+` (Note that only finds multiple initials, for single initials you can adjust the regex and make sure to use case-sensitive)

**Comment by acabal** [comment]
Make sure to get the names in the colophon too; and M.D. should be set without periods per the typography manual

**Comment by drgrigg** [comment]
I'm not sure about why I should use the <abbr clas="name"> tags in the colophon, as these names are already within <span class="name">?
